name: Build LineageOS 14.1 for Tank

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1️⃣ Checkout this repo
      - name: Checkout workflow repo
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK 8 using Temurin
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: temurin

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y \
            bison build-essential ccache curl flex g++-multilib gcc-multilib git \
            gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev \
            lib32z1 liblz4-tool libncurses-dev libsdl1.2-dev libssl-dev \
            libxml2 lzop pngcrush rsync squashfs-tools xsltproc zip zlib1g-dev

      # 4️⃣ Install repo tool
      - name: Install repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      # 5️⃣ Initialize repo
      - name: Initialize repo
        run: |
          mkdir -p ~/android/lineage
          cd ~/android/lineage
          repo init -u https://github.com/LineageOS/android.git -b cm-14.1

      # 6️⃣ Sync repo
      - name: Sync repo
        run: |
          cd ~/android/lineage
          repo sync -j$(nproc)

      # 7️⃣ Clone device-specific repositories
      - name: Clone device-specific repositories
        run: |
          cd ~/android/lineage
          git clone https://github.com/cmtank/device_amazon_tank.git -b cm-14.1 device/amazon/tank
          git clone https://github.com/cmtank/android_kernel_amazon_mt8127.git -b cm-14.1 kernel/amazon/mt8127
          git clone https://github.com/cmtank/vendor_amazon_tank.git vendor/amazon/tank

      # 8️⃣ Set up build environment and build ROM
      - name: Build ROM
        run: |
          cd ~/android/lineage
          bash -c "source build/envsetup.sh && lunch lineage_tank-userdebug && make -j$(nproc)"
